<?php

define('HTTP_SUCCESS', 200);
define('HTTP_NO_CONTENT', 204);
define('HTTP_MOVED_PERMANENTLY', 304);
define('HTTP_BAD_REQUEST', 400);
define('HTTP_UNAUTHORIZED', 401);
define('HTTP_FORBIDDEN', 403);
define('HTTP_NOT_FOUND', 404);
define('HTTP_NOT_ACCEPTABLE', 406);
define('HTTP_TIMEOUT', 408);
define('HTTP_CONFLICT', 409);
define('HTTP_GONE', 410);
define('HTTP_PRECONDITION_FAILED', 412);
define('HTTP_UNSUPPORTED_MEDIA', 415);
define('HTTP_TOO_LARGE', 413);
define('HTTP_EXPECTATION_FAIL', 417);
define('HTTP_TEAPOT', 418);
define('HTTP_UNPROCESSABLE', 422);
define('HTTP_SERVER_ERROR', 500);
define('HTTP_NOT_IMPLEMENTED', 501);
define('HTTP_UNAVAILABLE', 503);
define('HTTP_SUSPENDED', 530);
